// Code generated by MockGen. DO NOT EDIT.
// Source: /home/wil/dev/sro/character-service/pkg/repository/inventory.go
//
// Generated by this command:
//
//	mockgen -source=/home/wil/dev/sro/character-service/pkg/repository/inventory.go -destination=/home/wil/dev/sro/character-service/pkg/repository/mocks/inventory.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	inventory "github.com/ShatteredRealms/character-service/pkg/model/inventory"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockInventoryRepository) AddItem(ctx context.Context, characterId *uuid.UUID, item *inventory.ItemInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, characterId, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockInventoryRepositoryMockRecorder) AddItem(ctx, characterId, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockInventoryRepository)(nil).AddItem), ctx, characterId, item)
}

// GetInventory mocks base method.
func (m *MockInventoryRepository) GetInventory(ctx context.Context, characterId *uuid.UUID) (inventory.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventory", ctx, characterId)
	ret0, _ := ret[0].(inventory.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventory indicates an expected call of GetInventory.
func (mr *MockInventoryRepositoryMockRecorder) GetInventory(ctx, characterId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventory", reflect.TypeOf((*MockInventoryRepository)(nil).GetInventory), ctx, characterId)
}

// RemoveItem mocks base method.
func (m *MockInventoryRepository) RemoveItem(ctx context.Context, characterId *uuid.UUID, item *inventory.ItemInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", ctx, characterId, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockInventoryRepositoryMockRecorder) RemoveItem(ctx, characterId, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockInventoryRepository)(nil).RemoveItem), ctx, characterId, item)
}

// SetInventory mocks base method.
func (m *MockInventoryRepository) SetInventory(ctx context.Context, characterId *uuid.UUID, arg2 *inventory.Inventory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInventory", ctx, characterId, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInventory indicates an expected call of SetInventory.
func (mr *MockInventoryRepositoryMockRecorder) SetInventory(ctx, characterId, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInventory", reflect.TypeOf((*MockInventoryRepository)(nil).SetInventory), ctx, characterId, arg2)
}

// SetQuantity mocks base method.
func (m *MockInventoryRepository) SetQuantity(ctx context.Context, characterId *uuid.UUID, item *inventory.ItemInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetQuantity", ctx, characterId, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetQuantity indicates an expected call of SetQuantity.
func (mr *MockInventoryRepositoryMockRecorder) SetQuantity(ctx, characterId, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetQuantity", reflect.TypeOf((*MockInventoryRepository)(nil).SetQuantity), ctx, characterId, item)
}
